#!/bin/bash

sleeptime="1" #Set seconds between every read
desttemp="/home/temp.txt"  #Destination of temp file
mintemp="27" #Temp where GPIO should shut off
turnon="command" #insert command for turning on pins.
turnoff="command" #insert command for turning off pins

state="state"
newtemp=$( cat $desttemp )

#Function checks temperature and calls either shutOff or turnOn.
checkTemp (){
echo "Checking temp"

if [ "$newtemp" -lt "$mintemp" ]; then
        state="1"
        shutOff
elif [ "$mintemp" -lt "$newtemp" ]; then
        state="0"
        turnOn
else
        turnOn
fi
}

#Shuts off pins while newtemp is lower than mintemp
shutOff (){
while [ "$newtemp" -lt "$mintemp" ]; do

newtemp=$( cat $desttemp )

if [ $state = "0" ]; then
        sleep $sleeptime
        echo "Temperature is currently below $mintemp, pins are still turned off."
        shutOff
elif [ $state = "1" ]; then
        echo "Turning off pins"
        $turnoff
        state="0"
        shutOff
fi
done
turnOn
}


#turns on pins while newtemp is higher than mintemp

turnOn (){
while [ "$mintemp" -lt "$newtemp" ]; do

newtemp=$( cat $desttemp )

if [ $state = "1" ]; then
        sleep $sleeptime
        echo "Temperature is currently above $mintemp, pins are still turned on."
        turnOn
elif [ $state = "0" ]; then
        echo "Turning on pins"
        $turnon
        state="1"
        turnOn
fi
done
shutOff
}


checkTemp
