#!/bin/bash

sleeptime="1" #Set seconds between every read
desttemp="/home/temp.txt"  #Destination of temp file
mintemp="27" #Temp where GPIO should shut off
turnon="command" #insert command for turning on pins.
turnoff="command" #insert command for turning off pins

state="2"
newtemp=$( cat $desttemp )

#Function checks temperature and calls either shutOff or turnOn.
checkTemp (){

sleep $sleeptime

echo "Checking temp"


if [ "$newtemp" -lt "$mintemp" ]
	state="1"
        then shutOff
elif [ "$mintemp" -lt "$newtemp" ]
        state="2"
	then turnOn
else
	turnOn
fi

}

#Shuts off pins while newtemp is lower than mintemp
shutOff (){


while [ "$newtemp" -lt "$mintemp" ]; do
newtemp=$( cat $desttemp )
if [ $state = "0" ]
	sleep $sleeptime
        then  echo "Temperature is currently below $mintemp, pins are still turned off."
        shutOff
elif [ $state = "1" ]
	then echo "Turning off pins"
	#$turnoff
	state="0"
	shutOff
fi
done
turnOn
}

#turns on pins while newtemp is higher than mintemp

turnOn (){

sleep $sleeptime
while [ "$mintemp" -lt "$newtemp" ]; do
newtemp=$( cat $desttemp )
if [ $state = "1" ]
        then  echo "Temperature is currently above $mintemp, pins are still turned on."
        turnOn
elif [ $state = "0" ]
        then echo "Turning on pins"
        #$turnon
        state="1"
        turnOn
fi
done
turnOff
}


checkTemp
